
services:
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nerd1990
      POSTGRES_DB: nest
    networks:
      - nest-estagio
    command: sleep 2
networks: 
    nest-estagio:
