version: '3.8'

services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nerd1990
      POSTGRES_DB: nest
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-estagio

  nestjs-test-api:
    build: .
    container_name: nestjs-test-api
    depends_on:
      - dev-db
    environment:
      DATABASE_URL: postgresql://postgres:nerd1990@dev-db:5432/nest?schema=public
    ports:
      - "3000:3000"
    networks:
      - nest-estagio

networks:
  nest-estagio:

volumes:
  pgdata:
