version: "3.8"

services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nerd1990
      POSTGRES_DB: nest
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-estagio
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nest"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  prisma-client:
    image: prisma/prisma-client-node
    depends_on:
      - dev-db
    networks:
      - nest-estagio

networks:
  nest-estagio:

volumes:
  pgdata:
